PennLINC/qsiprep

- docs/preprocessing.rst
- docs/usage.rst
- qsiprep/cli/run.py
- wrapper/qsiprep_singularity.py
This pull request will update qsiprep docs / usage only, and does not change any preprocessing or reconstruction workflows or code. 
This pull request updates docs and explanations of qsiprep arguments via updates to qsiprep_singularity.py, preprocessing.rst, usage.rst, and qsiprep/cli/run.py
qsiprep_singularity.py, preprocessing.rst, usage.rst, qsiprep/cli/run.py
> ENH Usage and Docs

- Dockerfile
- README.rst
- docs/citing.rst
- docs/reconstruction.rst
- qsiprep/data/pipelines/csdsi_3dshore.json
- qsiprep/data/pipelines/dipy_3dshore.json
- qsiprep/data/pipelines/dipy_mapmri.json
- qsiprep/data/pipelines/dsi_studio_gqi.json
- qsiprep/data/pipelines/mrtrix_dhollander.json
- qsiprep/data/pipelines/mrtrix_dhollander_no5tt.json
- qsiprep/data/pipelines/mrtrix_msmt_csd.json
- qsiprep/data/pipelines/mrtrix_tckglobal.json
- qsiprep/workflows/recon/anatomical.py
- wrapper/qsiprep_docker.py
- wrapper/qsiprep_singularity.py
- Add the whole Schaefer family of atlases
- Add brainnetome atlas
- Add Aicha Atlas
- Update documentation
- Closes #32 
- Closes #34
> [ENH] Add many new atlases and documentation

- .circleci/config.yml
- qsiprep/cli/version.py
- versioneer.py
fixes a copy/paste error that was causing 0+unknown to be the version in the container
> [FIX] Make static versioning work in container

- qsiprep/cli/run.py
- qsiprep/utils/sentry.py
- setup.cfg
Attaches a sentry instance to qsiprep
None
> [ENH] add sentry for stats

- .circleci/config.yml
- .circleci/local_test.sh
- qsiprep/cli/run.py
- wrapper/qsiprep_docker.py
- wrapper/qsiprep_singularity.py
> [ENH] Use official bids apps commandline format

- .circleci/config.yml
- .circleci/local_test.sh
- docs/quickstart.rst
- qsiprep/cli/run.py
- wrapper/qsiprep_docker.py
- wrapper/qsiprep_singularity.py
Update documentation to reflect changes made in #65
> [DOCS] Update documentation for BIDS App arguments

- qsiprep/cli/run.py
> [ENH] Better error reporting for an empty --output-resolution

- qsiprep/cli/run.py
- qsiprep/interfaces/eddy.py
- qsiprep/workflows/dwi/fsl.py
Make sure eddy has access to multiple threads, if available.
> [ENH] let eddy use OMP_NUM_THREADS

- .circleci/config.yml
- .circleci/local_test.sh
- qsiprep/interfaces/eddy.py
- qsiprep/interfaces/fmap.py
- qsiprep/interfaces/images.py
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/fsl.py
- qsiprep/workflows/dwi/pre_hmc.py
> [FIX] Combine-all-dwis

- qsiprep/workflows/dwi/fsl.py
* Convert CNR map from eddy into LPS+ before warping
* Closes #72
> [FIX] Reorient eddy CNR maps

- qsiprep/interfaces/images.py
- qsiprep/interfaces/reports.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/merge.py
- qsiprep/workflows/dwi/pre_hmc.py
- qsiprep/workflows/dwi/util.py
Adds back in image header checking. This helps with #74
> [ENH] Reintroduce image header validation

- docs/preprocessing.rst
Documention change for carpet plot
> [DOC] Update preprocessing.rst

- .circleci/local_test.sh
- docs/preprocessing.rst
- qsiprep/interfaces/anatomical.py
- qsiprep/interfaces/reports.py
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/qc.py
gives an idea of coregistration success
> [ENH] Add Dice scores to ImageQC

- qsiprep/interfaces/nilearn.py
- qsiprep/workflows/fieldmap/syn.py
Bad masking was causing SyN-SDC and distortion correction workflows to fail. This raises an exception if no viable mask is found.
> [FIX] Add a fallback method if gradmax masking doesn't work

- qsiprep/interfaces/niworkflows.py
Remove extra transpose as reported in #120
> [FIX] Remove unnecessary transpose

- qsiprep/workflows/anatomical.py
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/confounds.py
- qsiprep/workflows/recon/base.py
Edits boilerplate text to match the manuscript
> [DOC] Edit boilerplate text to match manuscript

- setup.cfg
There have been issues with the ODF rendering due to some updates in VTK not being compatible with the OpenGL libraries in the container. Addresses #159 
This might fix #141 as well
> [BUG] Fix/odf plots

- qsiprep/interfaces/dwi_merge.py
> [DOC] Add better error for when hcp-style merge is not possible

- qsiprep/data/pipelines/mrtrix_multishell_msmt_noACT.json
- qsiprep/data/pipelines/mrtrix_singleshell_ss3t.json
- qsiprep/data/pipelines/mrtrix_singleshell_ss3t_noACT.json
Rename recon workflows so their directories are correctly named #150
> [FIX] Recon workflow names

- .circleci/config.yml
- qsiprep/workflows/base.py
> [FIX] --dwi-only fails when there's no T1w

- Dockerfile
The file /cmake-3.11.4-Linux-x86_64.sh is used for compiling ANTs but is left in the container root directory. Removing it saves 33 Mb.
None
> FIX: remove cmake installer after compiling ANTs

- qsiprep/interfaces/dipy.py
Changes patch2self defaults based on https://github.com/dipy/dipy/issues/2334
> [ENH] Change patch2self defaults

- docs/contributors.rst
- qsiprep/cli/run.py
- qsiprep/data/pipelines/dipy_3dshore.json
- qsiprep/workflows/recon/base.py
- requirements.txt
- setup.cfg
It's very useful to have a bids database directory if there are many files in the BIDS directory. 
This adds a `--bids-database-dir` option. #217
Also adds filters to the BIDSLayout to work with Datalad datasets
> [ENH] Add bids database option

- qsiprep/cli/run.py
- qsiprep/data/pipelines/dipy_3dshore.json
- qsiprep/workflows/recon/base.py
The 3dshore workflow wasn't doing tractography after some interfaces got refactored #242
> [FIX] Add tractography to dipy_3dshore workflow

- qsiprep/interfaces/dsi_studio.py
There's a LR + AP flip in the scalar images that come out of DSI Studio. Addresses #241
> [FIX] flip scalar images from DSI Studio

- qsiprep/cli/run.py
> [ENH] remove deprecated options

- Dockerfile
- qsiprep/cli/run.py
- qsiprep/niworkflows/utils/bids.py
- qsiprep/utils/bids.py
- qsiprep/workflows/base.py
- wrapper/qsiprep_docker.py
- wrapper/qsiprep_singularity.py
Adds an option to filter BIDS inputs
> [ENH] Add option for a BIDS filter file

- qsiprep/interfaces/reports.py
Addresses #265 by using a workaround to get equal axes
> [FIX] fix scaling in qspace scheme report

- .circleci/DSDTI_outputs.txt
- .circleci/config.yml
- Dockerfile
- docs/citing.rst
- docs/reconstruction.rst
- qsiprep/cli/run.py
- qsiprep/data/boilerplate.bib
- qsiprep/data/pipelines/amico_noddi.json
- qsiprep/data/pipelines/reorient_fslstd.json
- qsiprep/interfaces/amico.py
- qsiprep/interfaces/converters.py
- qsiprep/interfaces/dsi_studio.py
- qsiprep/interfaces/reports.py
- qsiprep/niworkflows/utils/bids.py
- qsiprep/utils/bids.py
- qsiprep/viz/recon_config.json
- qsiprep/workflows/base.py
- qsiprep/workflows/recon/amico.py
- qsiprep/workflows/recon/build_workflow.py
- qsiprep/workflows/recon/converters.py
- qsiprep/workflows/recon/dsi_studio.py
- setup.cfg
- wrapper/qsiprep_docker.py
- wrapper/qsiprep_singularity.py
Add the AMICO package so qsiprep can reconstruct the NODDI model
TODO:
-------
Refer to https://github.com/cookpa/amico-noddi
> [ENH] Add NODDI/AMICO recon workflows

- docs/quickstart.rst
Adding the `ses` label to BIDS paths in the quickstart guide, since there was some confusion without them on how to build IntendedFor paths without it.
The Quickstart Guide is the only currently proposed change
> ENH: Clarifying Documentation

- docs/preprocessing.rst
Fix reference to `--combine-before-denoising` which should be `--denoise-after-combining`.
Section on merging and denoising
> DOC: "denoise-after-combining" is the CLI option

- .zenodo.json
- qsiprep/niworkflows/utils/bids.py
using Path.resolve() broke some legacy niworkflows bids handling code.
> [FIX] Fieldmap bug when using datalad

- docs/preprocessing.rst
Explain how to use BIDS filters.
preprocessing.rst
> Bids filter doc

- qsiprep/utils/bids.py
Small change to the text of the pipeline dataset_description.json file to add a link to the citation information on the journal website.
> Adds link to citation in dataset_description.json

- qsiprep/interfaces/patch2self.py
> [FIX] change patch2self to use the nipype logger

- qsiprep/niworkflows/viz/utils.py
> [FIX] Undead xvfb processes in singularity

- .zenodo.json
- docs/installation.rst
Examples of mounting the Freesurfer license.txt given to prevent issues similar to #325
Changed the installation page of the docs to include examples of mounting the Freesurfer license.txt given to prevent issues running Freesurfer workflows in Docker or Singularity containers of QSIPrep - similar to #325 (closed with the method used in the added examples).
Since no change was made to the qsiprep tool itself in this PR, changes to documentation consist of the added example run commands. I think anyone choosing the option of running Freesurfer here likely already knows how to get the necessary license for their work, but it might be worth adding a link if not.
> ENH: Explain mounting Freesurfer license.txt to Docker & Singularity

- .circleci/DIPYReconTests.sh
- qsiprep/interfaces/dipy.py
- qsiprep/workflows/recon/dipy.py
> [FIX] spelling and fix defaults

- qsiprep/interfaces/ants.py
- qsiprep/workflows/dwi/resampling.py
- setup.cfg
Addresses #387, #379, closes #152.
> [FIX] Properly transform the 4D CNR images from Eddy

- .circleci/config.yml
- Dockerfile
- setup.cfg
Updates qsiprep_build to 22.4.1
TODO:
> [ENH] update amico version, switch to 22.4.1

- qsiprep/interfaces/mrtrix.py
- qsiprep/workflows/recon/mrtrix.py
Adds files needed to inspect connectomes in mrview when you run any of the mrtrix reconstruction pipelines
> [ENH] Add exemplar streamlines to mrtric connectivity workflows

- .circleci/config.yml
- Dockerfile
- qsiprep/data/pipelines/csdsi_3dshore.json
- qsiprep/data/pipelines/dipy_3dshore.json
- qsiprep/data/pipelines/dsi_studio_gqi.json
- qsiprep/data/pipelines/mrtrix_multishell_msmt_ACT-fast.json
- qsiprep/data/pipelines/mrtrix_multishell_msmt_ACT-hsvs.json
- qsiprep/data/pipelines/mrtrix_multishell_msmt_noACT.json
- qsiprep/data/pipelines/mrtrix_singleshell_ss3t_ACT-fast.json
- qsiprep/data/pipelines/mrtrix_singleshell_ss3t_ACT-hsvs.json
- qsiprep/data/pipelines/mrtrix_singleshell_ss3t_noACT.json
- qsiprep/data/pipelines/mrtrix_tckglobal.json
- qsiprep/data/pipelines/pyafq_input_trk.json
This PR adds subcortical regions to the qsiprep default atlases
> [ENH] Use updated atlases

- .circleci/config.yml
- Dockerfile
> [FIX] schaefer400 atlas

- qsiprep/data/pipelines/mrtrix_multishell_msmt_ACT-fast.json
- qsiprep/data/pipelines/mrtrix_multishell_msmt_ACT-hsvs.json
- qsiprep/data/pipelines/mrtrix_multishell_msmt_noACT.json
- qsiprep/data/pipelines/mrtrix_singleshell_ss3t_ACT-fast.json
- qsiprep/data/pipelines/mrtrix_singleshell_ss3t_ACT-hsvs.json
- qsiprep/data/pipelines/mrtrix_singleshell_ss3t_noACT.json
- qsiprep/interfaces/dsi_studio.py
- qsiprep/interfaces/mrtrix.py
- qsiprep/workflows/recon/mrtrix.py
Turns out that connectome2tck is very slow when 10mil streamlines need to be processed. This sets up multicore processing for c2t
> [ENH] optimize connectome2tck

- .circleci/config.yml
- Dockerfile
In preparation for including TORTOISE, we need to update ANTs to use ITK 5.3.
> [ENH] update itk to 5.3

- qsiprep/interfaces/__init__.py
- qsiprep/interfaces/bids.py
- qsiprep/interfaces/eddy.py
- qsiprep/interfaces/fmap.py
- qsiprep/interfaces/tortoise.py
- qsiprep/niworkflows/viz/utils.py
- qsiprep/viz/config.json
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/fsl.py
- qsiprep/workflows/dwi/hmc_sdc.py
- qsiprep/workflows/dwi/registration.py
- qsiprep/workflows/fieldmap/drbuddi.py
- qsiprep/workflows/fieldmap/pepolar.py
Create visual reports that highlight the many features of DRBUDDI
> [ENH] Add visual reports for DRBUDDI

- .circleci/DSDTI_nofmap.sh
- .circleci/config.yml
- pyproject.toml
- qsiprep/cli/run.py
- qsiprep/data/boilerplate.bib
- qsiprep/interfaces/tortoise.py
- qsiprep/utils/bids.py
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/merge.py
- setup.cfg
- setup.py
Add the `Gibbs` program from TORTOISE. This is method is designed specifically for partial fourier acquisitions
> [ENH] Add "Gibbs" from TORTOISE

- qsiprep/workflows/dwi/hmc.py
- qsiprep/workflows/dwi/hmc_sdc.py
> [FIX] SHORELine + DRBUDDI transforms

- qsiprep/niworkflows/interfaces/registration.py
Issue arose in #519, since we don't contain freesurfer or offer bbr this fixes fs version
> [FIX] int/str comparison when loading freesurfer

- qsiprep/cli/run.py
- qsiprep/interfaces/shoreline.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/hmc.py
add single tensor model to shoreline head motion correction
> add DTI to shoreline

- qsiprep/interfaces/anatomical.py
- qsiprep/niworkflows/anat/ants.py
- qsiprep/workflows/anatomical.py
- qsiprep/workflows/fieldmap/fmap.py
- qsiprep/workflows/fieldmap/unwarp.py
- qsiprep/workflows/fieldmap/utils.py
Addresses one component of https://github.com/PennLINC/qsiprep/issues/482.
Creates new interface, CustomApplyMask, to apply a mask to another image without using FSL. Only actually used in surface recon anatomical workflow a single time. Other calls to FSL applymask are in workflows so dependent on FSL that there is no ability to replace the functionality of FSL entirely. Those calls were left as-is, with the addition of a check for an FSL environment variable. If FSL isn't found, this check will throw an error indicating that the FSL-less container is being used.
No documentation or usage changes required.
> ENH: Replace fsl applymask

- .circleci/config.yml
- Dockerfile
- setup.cfg
Include @eurotomania's new method for T2w registration in DRBUDDI
> [ENH] Update TORTOISE for improved T2w registration

- qsiprep/workflows/recon/anatomical.py
Under some circumstances qsiprep may write non-gzipped T1ws (note: look into this too). Recon workflows should be ok with using these unzipped files. Addresses #585
> [FIX] allow non-gzipped T1ws for recon workflows

- qsiprep/workflows/dwi/distortion_group_merge.py
> [FIX] add btable to merge when averaging outputs

- .circleci/DRBUDDI_TENSORLine_epi.sh
- .circleci/config.yml
- qsiprep/interfaces/dsi_studio.py
- qsiprep/interfaces/shoreline.py
Adds a CI test for the tensor-based head motion correction. It will be failing at first, so also a bugfix to get the test to pass
> [CI] Add test for tensor-based head motion correction

- qsiprep/interfaces/freesurfer.py
> [FIX] Forces synthseg to use 1 thread

- qsiprep/utils/bids.py
Fix #630, while conserving compatibility with prior versions (keeping the "PipelineDescription" field).
> Fix #630 — update in BIDS dataset_description

- docs/help.rst
- docs/index.rst
> DOD: Document how to obtain help

- .zenodo.json
- docs/reconstruction.rst
Slight update to documentation to include the currently mandatory flag if doing reconstruction only: ``--recon-only``.
In ``reconstruction.rst``.
> DOC: add `--recon-only` flag in `reconstruction.rst`

- .zenodo.json
Add SMeisler and JHLegarreta to contributors list.
> DOC: Add SMeisler and JHLegarreta to contributors list

- .circleci/HBCD_preproc.sh
- .circleci/get_data.sh
- qsiprep/cli/run.py
- qsiprep/interfaces/eddy.py
- qsiprep/interfaces/tortoise.py
- qsiprep/viz/config.json
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/fsl.py
- qsiprep/workflows/dwi/hmc_sdc.py
- qsiprep/workflows/fieldmap/drbuddi.py
Adds an option for `--pepolar-method TOPUP+DRBUDDI`
TODO:
> [ENH] allow topup+drbuddi for hbcd

- .circleci/config.yml
- Dockerfile
- pyproject.toml
> [ENH] Update to python 3.10

- .circleci/MultiT1w.sh
- .circleci/config.yml
- Dockerfile
> [ENH] Update BIDS validator to 1.8.4

- .circleci/TortoiseRecon.sh
- .circleci/config.yml
- .circleci/get_data.sh
- pyproject.toml
- qsiprep/data/pipelines/TORTOISE.json
- qsiprep/data/pipelines/TORTOISE_mapmri.json
- qsiprep/interfaces/recon_scalars.py
- qsiprep/interfaces/tortoise.py
- qsiprep/workflows/recon/build_workflow.py
- qsiprep/workflows/recon/tortoise.py
- wrapper/pyproject.toml
- wrapper/qsiprep_container/qsiprep_docker.py
- wrapper/qsiprep_container/qsiprep_singularity.py
> [ENH] Add TORTOISE Estimator recon workflows

- .circleci/config.yml
Closes none.
- Fix path in `.circleci/config.yml`. I'm not sure if this is sufficient to fix the problem, but it's a start.
> Fix deployment bug

- qsiprep/interfaces/bids.py
- qsiprep/workflows/recon/anatomical.py
> [FIX] save recon anat files

- qsiprep/interfaces/dsi_studio.py
closes #664
I was able to reproduce #664 while running in docker on my laptop. It appears to be related to https://github.com/nipy/nipype/issues/2265. This change got rid of the error locally, but the error has never appeared in the CI tests.
> [FIX] Prevent undecodable terminal output in calc_connectivity

- .circleci/CUDATest.sh
- .circleci/config.yml
- .circleci/get_data.sh
- Dockerfile
- qsiprep/interfaces/dsi_studio.py
- qsiprep/interfaces/freesurfer.py
- qsiprep/interfaces/tortoise.py
- qsiprep/workflows/dwi/util.py
- wrapper/qsiprep_container/qsiprep_docker.py
- wrapper/qsiprep_container/qsiprep_singularity.py
Due to significant bugs in FSL, and FSL's new conda-based installation system there had to be a major overhaul of the qsiprep_build docker image.
> [FIX] Update Everything

- .circleci/config.yml
- Dockerfile
Switch to the cuda runtime image and tensorflow gpu will work for synthseg
> [ENH] update base image for cuda

- qsiprep/data/pipelines/csdsi_3dshore.json
Removed "streamline_connectivity" and "controlability" nodes from csdsi_3dshore.json pipeline spec, as they were old and lead to crashes.
See: https://neurostars.org/t/error-when-using-csdsi-3dshore-recon-possible-spec-fix/29184
> [FIX] remove old nodes from csdsi_3dshore.json

- qsiprep/data/pipelines/hbcd_scalar_maps.json
- qsiprep/interfaces/scalar_mapping.py
Fits some nice models and maps them to bundles and to template space.
> [ENH] Add recon workflow for hbcd beta

- .circleci/config.yml
- qsiprep/interfaces/fmap.py
- qsiprep/workflows/dwi/fsl.py
qsiprep has too many templates in the python package right now, so until we switch to templateflow, disable pypi
> [MAINT] remove pypi

- qsiprep/interfaces/fmap.py
- qsiprep/workflows/dwi/fsl.py
adds the option to parallelize topup. Closes #715, a minor variation of #737
> [ENH] add parallel argument for topup

- qsiprep/interfaces/eddy.py
`eddy_cpu` ignores `OMP_NUM_THREADS` and requires a `--nthr=N` argument instead
> [ENH] Allow multithreading in eddy

- qsiprep/tests/data/pyafq_recon_full_optional_outputs.txt
Make some AFQ bundles optional in the CI tests
> [CI] add optional bundles

- .circleci/3TissueAutotrackTest.sh
- qsiprep/data/pipelines/ss3t_autotrack.json
- qsiprep/interfaces/converters.py
- qsiprep/tests/utils.py
- qsiprep/workflows/recon/build_workflow.py
- qsiprep/workflows/recon/converters.py
> [FIX] Fix the mif2fib workflow

- qsiprep/tests/data/mrtrix3_recon_outputs.txt
- qsiprep/tests/data/mrtrix_singleshell_ss3t_act_outputs.txt
- qsiprep/tests/data/mrtrix_singleshell_ss3t_noact_outputs.txt
- qsiprep/tests/data/pyafq_recon_external_trk_optional_outputs.txt
- qsiprep/tests/data/pyafq_recon_external_trk_outputs.txt
- qsiprep/workflows/recon/mrtrix.py
Addresses #772
Currently the SIFT2 mu parameter is connected to mu in the `outputnode`, but is never written to the output folder. Given that this is a necessary correction factor when using sum of streamlines connectomes after SIFT2, this will write the mu parameter to the derivatives folder.
> Save SIFT2 mu parameter

- qsiprep/data/pipelines/hbcd_scalar_maps.json
> [FIX] Update bundle list for hbcd_scalar_maps

- .circleci/config.yml
- Dockerfile
- qsiprep/interfaces/dsi_studio.py
Update to include the bleeding edge release of DSI Studio
> [ENH] Update DSI Studio to Hao

- .circleci/config.yml
- pyproject.toml
- qsiprep/data/boilerplate.bib
- qsiprep/tests/test_cli.py
> [CI] Update CI to be more efficient

- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/distortion_group_merge.py
> [FIX] use correct arguments for merging distortion groups

- qsiprep/data/reports-spec.yml
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/merge.py
> [FIX] Add denoising reportlets back to html

- qsiprep/utils/grouping.py
Closes #860.
- Rename `get_session_groups` to `get_entity_groups`.
- Generalize `get_entity_groups` to group scans within both session _and_ acquisition. The addition of acquisition is new.
> Make grouping account for acquisition entity

- qsiprep/data/boilerplate.bib
- qsiprep/workflows/base.py
Closes #486.
- Add QSIPrep paper to boilerplate and bibtex file.
> Add QSIPrep paper to boilerplate

- docs/installation.rst
Closes #626.
- Improve installation instructions, including info about installing with pip.
> Add instructions for installing with pip

- README.rst
- docs/contributors.rst
> Add Zenodo badge to README

- CONTRIBUTING.md
added link to fmriprep style guide in order to check off NMIND item
> Link to NiPreps contributing guidelines

- pyproject.toml
- qsiprep/reports/core.py
- qsiprep/utils/grouping.py
- qsiprep/utils/misc.py
Closes none.
- Fix up concatenation-related docstrings.
- Log concatenation-related groupings as they're compiled.
> Log steps of concatenation grouping

- pyproject.toml
Closes none.
- Increase DIpy version from 1.8.0 to 1.11.0.
> Bump dipy version

- qsiprep/interfaces/reports.py
- qsiprep/interfaces/tortoise.py
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/fsl.py
- qsiprep/workflows/dwi/hmc.py
- qsiprep/workflows/dwi/hmc_sdc.py
- qsiprep/workflows/dwi/resampling.py
> Add fieldmap in hz to derivatives + tabular stats
