- .circleci/config.yml
- .zenodo.json
- qsiprep/interfaces/eddy.py
- qsiprep/interfaces/fmap.py
- qsiprep/interfaces/images.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/fsl.py
- qsiprep/workflows/dwi/hmc.py
- qsiprep/workflows/dwi/merge.py
- qsiprep/workflows/dwi/pre_hmc.py
- qsiprep/workflows/dwi/util.py
- qsiprep/workflows/fieldmap/base.py
- qsiprep/workflows/fieldmap/pepolar.py
- qsiprep/workflows/fieldmap/unwarp.py
- qsiprep/workflows/recon/base.py
- qsiprep/workflows/recon/converters.py
- qsiprep/workflows/recon/dipy.py
Fieldmaps weren't being handled correctly in eddy, either from the sdc workflows (phasediff, phases) or from TOPUP. Topup only worked correctly with eddy if everything was in LAS+, so now that is the default for that workflow. Everything is converted back to LPS+ after eddy and sdc workflows happen to the eddy-corrected data. Closes #35.
> [FIX] Ensure fieldmaps are handled correctly around eddy

- qsiprep/interfaces/images.py
The `Conform` interface had an assertion error that isn't valid for LPS+ images. This was causing false error messages on some T1w input images.
> [BUG] Remove erroneous assertion error on conform_t1

- docs/preprocessing.rst
- qsiprep/cli/run.py
- qsiprep/interfaces/images.py
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/resampling.py
* Use BSpline interpolation if `--output-resolution` has a smaller voxel size than the inputs
> [ENH] Use BSpline interpolation when outputs have smaller voxels

- .zenodo.json
- qsiprep/cli/run.py
Skip BIDS validation when either `--skip-bids-validation` or `--recon-only` are supplied. 
Previously, both were need both to skip validation.
N/A unless previous behavior is intended, then maybe a note in `--skip_bids_validation`'s parser help text
> FIX: only run bids if not recon-only *and* not skip bids

- qsiprep/workflows/dwi/util.py
Use `CopyHeader` to make sure all images occupy exactly the same physical space before sending to N4
> [FIX] fix headers for N4 masks and weights

- qsiprep/interfaces/dsi_studio.py
- qsiprep/interfaces/fmap.py
- wrapper/qsiprep_docker.py
Currently there can be up to 12 images sent to topup if there were two dwi series with opposite phase encoding directions and two opposite epi fieldmaps. This PR forces only up to 6 images to be used: 3 per phase encoding direction. DWI b=0s are preferred over epi fieldmap b=0's.
> [ENH] Prevent too many images from being used by topup

- qsiprep/workflows/dwi/finalize.py
Sprites were breaking if there was an odd number of slices. Disabling the interactive viewer for 0.7
> [FIX] remove interactive report for now

- .circleci/DSCSDSI_outputs.txt
- .circleci/DSDTI_nofmap_outputs.txt
- .circleci/DSDTI_outputs.txt
- .circleci/DSDTI_synsdc_outputs.txt
- .circleci/IntramodalTemplate_outputs.txt
- docs/preprocessing.rst
- qsiprep/interfaces/ants.py
- qsiprep/interfaces/nilearn.py
- qsiprep/niworkflows/viz/utils.py
- qsiprep/viz/config.json
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/derivatives.py
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/fsl.py
- qsiprep/workflows/dwi/hmc.py
- qsiprep/workflows/dwi/hmc_sdc.py
- qsiprep/workflows/dwi/intramodal_template.py
- qsiprep/workflows/dwi/qc.py
- qsiprep/workflows/dwi/resampling.py
- qsiprep/workflows/dwi/util.py
- qsiprep/workflows/fieldmap/syn.py
- qsiprep/workflows/fieldmap/unwarp.py
- setup.cfg
The workflow introduced in 0.7.2 worked in most cases, but was not robust enough to cover all cases reasonably. This PR adds in a preliminary b=0 to T1w registration and uses the T1 brain mask for the early stages in the pipeline that require a mask (ie motion correction)
> [ENH] Make dwi masking more robust

- CHANGES.rst
- qsiprep/interfaces/images.py
- qsiprep/interfaces/nilearn.py
- qsiprep/workflows/anatomical.py
- setup.cfg
There were "Images do not occupy the same physical space" errors in skull stripping that arose due to oblique affines in T1w images. Since these get put in ACPC space anyways, there is no issue with removing the oblique affine and replacing it with one that preserves the center and voxel sizes. Fixes #74.
> [FIX] Deoblique T1w headers

- qsiprep/interfaces/dwi_merge.py
- qsiprep/interfaces/fmap.py
- qsiprep/interfaces/images.py
- qsiprep/utils/grouping.py
- qsiprep/workflows/dwi/pre_hmc.py
This includes multiple fixes for merging HCP-style scans
* Renames subworkflows to include `dir_`
* Re-purpose MergeDWIs to also merge across PE directions
* Replace ConcateRPESplits with a NiPype workflow
> [FIX] Rename workflows for HCP-style acquisitions

- CHANGES.rst
- docs/preprocessing.rst
- qsiprep/cli/run.py
- qsiprep/interfaces/dwi_merge.py
- qsiprep/interfaces/fmap.py
- qsiprep/interfaces/images.py
- qsiprep/interfaces/reports.py
- qsiprep/interfaces/utils.py
- qsiprep/utils/grouping.py
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/distortion_group_merge.py
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/merge.py
- qsiprep/workflows/dwi/pre_hmc.py
- qsiprep/workflows/dwi/qc.py
- qsiprep/workflows/dwi/resampling.py
The HCP pipelines run the same sampling scheme twice - once in each phase-encoding direction. Each phase-encoding direction version of the scheme is split into two files, resulting in 4 DWI scans. There are also a pair of EPI fieldmaps in the fmaps/ directory.
This PR adds the --distortion-group-merge option that can be 'none' (Default), 'average' (for HCP-style averaging) or 'concat' (produces a 4d series of the corrected input images).
> [ENH] Enable HCP-style polarity-pair image averaging

- .circleci/config.yml
The ManyLinux wheel maker was failing on bids validator. So now it's removed
> [FIX] remove manylinux

- .zenodo.json
- qsiprep/workflows/fieldmap/utils.py
This pull request removes the outdated NUMPY_MMAP import from nipype (ref. issue #172).
The other PR, got deleted, since I changed the name of my branch. Sorry for the mess.
> [FIX] Remove outdated `NUMPY_MMAP` calls

- qsiprep/interfaces/dipy.py
- qsiprep/interfaces/patch2self.py
- qsiprep/workflows/dwi/merge.py
- Better edge case handling for ex-vivo data. Handles negative values in the distribution of the data with shifting per-volume (added as an option) rather than clipping always. Preserves the variance of the intensity distribution.
- New option for skipping b0 denoising in totality. For some data, b0 denoising could get very messy. User may want to switch it off and denoise only DWI volumes.
p.s. These changes are in the merged in the master of DIPY 👍🏽
> Updates for Patch2Self

- docs/comparisons.md
- docs/preprocessing.rst
- docs/quickstart.rst
- docs/reconstruction.rst
- qsiprep/interfaces/anatomical.py
- qsiprep/interfaces/bids.py
- qsiprep/interfaces/dipy.py
- qsiprep/interfaces/dwi_merge.py
- qsiprep/utils/misc.py
- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/distortion_group_merge.py
- qsiprep/workflows/dwi/finalize.py
- qsiprep/workflows/dwi/qc.py
- qsiprep/workflows/recon/base.py
- qsiprep/workflows/recon/build_workflow.py
- qsiprep/workflows/recon/dsi_studio.py
Addresses #232 by averaging the carpetplots and motion parameters so they have the same number of samples as the images.
> [FIX] Change interactive reports to work with merged distortion groups

- .zenodo.json
- qsiprep/interfaces/dsi_studio.py
- qsiprep/workflows/dwi/qc.py
Two days ago we tripped over the fact that the use of [`os.link()` in dsi_studio.py](https://github.com/PennBBL/qsiprep/blob/master/qsiprep/interfaces/dsi_studio.py#L135) fails for file systems without or with limited hard link support ([BeeGFS](https://www.beegfs.io/wiki/FAQ#hardlinks) in our case). A quick fix would have been to just wrap it into a try-except block and use `shutil.copyfile()` on failure. However, I was curious what was going on in the interfaces and I found that the reason a tmp directory was created (at least for [DSIStudioSrcQC](https://github.com/PennBBL/qsiprep/blob/master/qsiprep/interfaces/dsi_studio.py#L106) was probably caused by some decision in the [DSI-Studio src](https://github.com/frankyeh/DSI-Studio/blob/ea38389afb12877211ad5bf9f2eb1630d0b33cc1/main.cpp#L74 …
> [ENH] improve dsi_studio qc interfaces and remove hard link dependency

- qsiprep/cli/run.py
Use a default working directory, to prevent an extremely user-unfriendly error message #222
> [FIX] use a default working dir

- qsiprep/workflows/base.py
#193 was reopened because the intramodal template workflow wasn't being created properly if --dwi-only was being used
> [FIX] --dwi-only should work with the intramodal template workflow

- .readthedocs.yml
- Dockerfile
AMICO couldn't find DIPY_HOME when run in a singularity container
> [FIX] specify DIPY_HOME in container

- Dockerfile
- qsiprep/interfaces/mrtrix.py
- qsiprep/workflows/dwi/merge.py
As pointed out in #269 the default FAST segmentation can be terrible. This PR will upgrade mrtrix so we can use HSV format
> [ENH] update mrtrix to 3.0.3

- .circleci/config.yml
- qsiprep/interfaces/dipy.py
- qsiprep/interfaces/patch2self.py
- qsiprep/viz/config.json
Fixes parameters upstream with `DIPY's Patch2Self`.
This is the reason why @SendyCaffarra was getting a bug. This issue was fixed in `Patch2Self` for DIPY in #2334 
[[PR Link]( https://github.com/dipy/dipy/issues/2334)]
Also setting default `'model='ols'`
I am also taking this opportunity to fix the naming [MP-PCA --> Generic "DWI Denoising"] in the reports.
> Crucial Fixes for Patch2Self

- qsiprep/interfaces/amico.py
- qsiprep/interfaces/dsi_studio.py
- qsiprep/workflows/recon/amico.py
- qsiprep/workflows/recon/dipy.py
- qsiprep/workflows/recon/dsi_studio.py
- qsiprep/workflows/recon/mrtrix.py
I've seen some strange behavior with cpu usage in the recon interfaces. This explicitly limits the number of cpus in the nipype node constructor and in the interface definition
> [ENH] add n_procs to recon nodes

- qsiprep/interfaces/confounds.py
The construction of the confounds matrix mixes pandas concat methods with direct addition of columns - the latter does not respect indices. Adding a call to sort_index reorganizes the FD / motion confounds data frame such that the indices are sequential. This means subsequent addition of columns with confounds['new_col'] = data work as expected, and the CSV file is written in the order most users would expect, with indices 0,1,...,N rather than 1,2,...N,0.
Fixes #397
> BUG: Fix misalignment of columns added to confounds matrix

- qsiprep/interfaces/dwi_merge.py
Some older data has bvals / bvecs of exactly 0, because the don't account for the non-diffusion gradients that make the real diffusion weighting slightly non-zero.
average_bvec now checks if gradients are identical first, if they are it just returns the answer without doing any of the normalization that leads to division by zero.
Fixes #375.
> BUG: Prevent divide by zero if bvec is all zeros

- .circleci/config.yml
- qsiprep/interfaces/utils.py
Issues #404, #415 and some Neurostars posts pointed out that the atlases from 0.15.x were not lining up with the T1w and dmri from qsiprep.
0.15.x had a refactored setup for anatomical data and some of the json files were changed to reflect this. This change interacted with the GetConnectivityAtlas class, which was missing the "T1w" space property and was just resampling the MNI atlas to the grid of the dmri data without any transforms.
> [FIX] Use correct transform for t1w-space data

- docs/environment.yml
- qsiprep/viz/recon_config.json
- qsiprep/workflows/recon/anatomical.py
- qsiprep/workflows/recon/base.py
- qsiprep/workflows/recon/build_workflow.py
- setup.cfg
in version 0.15.x many of the recon derivatives stopped appearing in the outputs. This PR adds back the connectivity plot #378 and should fix the multi-run reconstruction bug #381
> [FIX] Add atlases back into derivatives

- .circleci/config.yml
- Dockerfile
Addresses
* https://neurostars.org/t/cannot-run-qsiprep-missing-dependencies-fugue-prelude/22480
* https://neurostars.org/t/qsiprep-dependencies-error-fugue-prelude/23432
* #462
> [FIX] Add back fugue and prelude to the qsiprep image

- qsiprep/interfaces/dwi_merge.py
bval and bvec were switched, just noticed while investigating another issue.
> DOC: paste error in file descriptions

- .circleci/config.yml
- Dockerfile
- qsiprep/interfaces/converters.py
- qsiprep/interfaces/dipy.py
- qsiprep/interfaces/dsi_studio.py
- qsiprep/interfaces/fmap.py
- qsiprep/interfaces/freesurfer.py
- qsiprep/interfaces/gradients.py
- qsiprep/interfaces/images.py
- qsiprep/interfaces/nilearn.py
- qsiprep/interfaces/niworkflows.py
- qsiprep/interfaces/qc.py
- qsiprep/interfaces/shoreline.py
- qsiprep/interfaces/utils.py
- qsiprep/niworkflows/anat/ants.py
- qsiprep/niworkflows/interfaces/cifti.py
- qsiprep/niworkflows/interfaces/freesurfer.py
- qsiprep/niworkflows/interfaces/images.py
- qsiprep/niworkflows/interfaces/itk.py
- qsiprep/niworkflows/interfaces/masks.py
- qsiprep/niworkflows/interfaces/mni.py
- qsiprep/niworkflows/interfaces/registration.py
- qsiprep/niworkflows/interfaces/utils.py
- qsiprep/niworkflows/viz/plots.py
- qsiprep/niworkflows/viz/utils.py
- qsiprep/utils/bspline.py
- qsiprep/workflows/anatomical.py
- qsiprep/workflows/fieldmap/pepolar.py
- qsiprep/workflows/fieldmap/utils.py
- setup.cfg
This adds some great options for segmentation and skull stripping.
> [ENH] Update FreeSurfer to 7.3.1, dmri-amico to 1.5.4

- .circleci/PyAFQReconExternalTrk.sh
- .circleci/PyAFQReconTests.sh
- .circleci/config.yml
- qsiprep/interfaces/pyafq.py
- qsiprep/utils/sloppy_recon.py
Closes #422 and #434 by adding in the export all and choice of export functionality for pyAFQ.
I also want to reduce the runtime of the tests here. @mattcieslak , is there a way to change the parameters for one of the nodes in the json file for the test only? For example, I would like select here to be 1e4 instead of 1e6, but only when doing the circle CI tests: https://github.com/PennLINC/qsiprep/blob/80803117d8d2397b14b28668314f7e3258273447/qsiprep/data/pipelines/mrtrix_multishell_msmt_pyafq_tractometry.json#L35
> WIP: ENH: Make pyAFQ tests faster, add export all

- qsiprep/interfaces/reports.py
- qsiprep/workflows/dwi/resampling.py
Adds multiple columns to the imageqc.csv file. For each shell the in-brain CNR mean, median and standard deviation of Eddy's CNR values are recorded.
> [ENH] add CNR to the imageqc.csv

- setup.cfg
New pandas is causing an issue, pin it to < 2.0.0 for now
> [FIX] pin pandas version to < 2.0.0

- .zenodo.json
- qsiprep/interfaces/gradients.py
- setup.cfg
Related to Issue 482 (https://github.com/PennLINC/qsiprep/issues/482) but does not complete all changes required to close issue.
Changes almost entirely restricted to one file (interfaces/gradients.py), and mostly to the get_fsl_motion_params() function within that file. Previously the FSL tool avscale was used to extract motion parameters (rotation, translation, shear, and scale/zoom) from the affine transform produced by ANTs. This was replaced by a series of custom functions, an affine decompose from the transforms3d package, and a rotation vector conversion from scipy.
No documentation changes necessary. No changes to usage, and the CombineMotions class interfaces that calls this motion extraction function can be treated exactly the same as it was prior to the change.
> ENH: Replace avscale with non-fsl tools

- qsiprep/workflows/dwi/distortion_group_merge.py
Addresses #554. add `omp_nthreads` argument to `init_dwi_reference_wf`. Seems like the argument might have got dropped at some point?
Add `omp_nthreads` as first positional argument to `init_dwi_reference_wf`.
N/A
> [FIX] Update distortion_group_merge.py

- qsiprep/cli/run.py
I'm debugging an issue and found that this option is present in the cli code, but never used anywhere. This was added in  d08a171c46555446e56bb9eb142f035ec37f8451  and I **assume** it was made obsolete with the `bids-filter-file` argument?
I was about to use this option when I figured out it would have made no difference anyway and I want to save others from falling into this little trap.
> [FIX] remove pre bids-filter acq type argument

- qsiprep/workflows/recon/anatomical.py
The autotrack workflow can run on inputs that were processed with --dwi-only. They weren't getting the correct inputs
> [FIX] connect dwi inputs to recon workflows when --dwi-only was enabled

- .circleci/AutoTrackTest.sh
- .circleci/config.yml
- Dockerfile
- qsiprep/interfaces/dsi_studio.py
- qsiprep/utils/sloppy_recon.py
- qsiprep/workflows/recon/dsi_studio.py
The AutoTrack workflow is constantly being killed on HPCs. This attempts to add some robustness to the run, which may or may not make a difference
> [ENH] Stabilize autotrack performance

- qsiprep/workflows/anatomical/volume.py
synthseg and synthstrip don't benefit much from multiple cpu usage, but the multithreading causes an enormous amount of memory to be used.
This fixes the number of threads at run time, but still occupies `omp_nthreads` in nipype
Addresses #595, #598
> [ENH] limit the synths to 1 thread

- .github/config.yml
- .zenodo.json
- docs/pull_request_template.md
Rework the PR template and first time contributor message:
- Edit and reword as necessary the PR template and first time
contributor message config files so that the first time contribution
information is not duplicated.
- Instruct new contributors to add their names to the list in
alphabetical order: reorder contributors alphabetically, keeping
Cieslak, Matthew as first and and Satterthwaite, Theodore D. as last
authors.
- Make the order of the contributor fields consistent: name,
affiliation, orcid.
- Slightly reword the first time contributor placeholder tags in the
first time contributor message config file.
- Remove the mention to Russell Poldrack as an author of the tool from
the PR template: Russell is not actually listed as an author in the
`.zenodo.json` file. Most likely this …
> ENH: Rework the PR template and first time contributor message

- docs/installation.rst
Remove the destination paths for the input and output binding input arguments in the `Docker` and `Singularity` container usage instructions.
Avoids, for example, errors that mean that no (BIDS) data was effectively found, e.g.:
```
Process Process-2:
Traceback (most recent call last):
File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 833, in build_qsiprep_workflow
layout = BIDSLayout(
File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 135, in __init__
root, description = validate_root(root, …
```
> DOC: Remove the destination paths in container documentation

- qsiprep/interfaces/interchange.py
- qsiprep/interfaces/mrtrix.py
- qsiprep/workflows/recon/amico.py
- qsiprep/workflows/recon/anatomical.py
- qsiprep/workflows/recon/base.py
- qsiprep/workflows/recon/build_workflow.py
- qsiprep/workflows/recon/converters.py
- qsiprep/workflows/recon/dipy.py
- qsiprep/workflows/recon/dsi_studio.py
- qsiprep/workflows/recon/dynamics.py
- qsiprep/workflows/recon/mrtrix.py
- qsiprep/workflows/recon/pyafq.py
- qsiprep/workflows/recon/steinhardt.py
- qsiprep/workflows/recon/utils.py
- qsiprep/workflows/reports.py
There are surprising bugs when trying to run reconstruction workflows on multi-session data. This PR will fix those. Thanks to @mayayab for reporting and providing testing data
> [FIX] Make recon workflows work on multi-session data

- docs/quickstart.rst
Clarify the output space convention: make it clear that all data is according to the AC-PC convention, and describe the changes this implies to the data.
> DOC: Clarify the output space convention

- qsiprep/data/pipelines/csdsi_3dshore.json
- qsiprep/data/pipelines/dipy_3dshore.json
The csdsi workflows were out of date with the current DSI Studio tractography interface
> [FIX] remove unneeded "method" from tracking

- qsiprep/data/pipelines/dsi_studio_gqi.json
Some parameters are no longer supported:
"seed_plan": used to control voxel or sub-voxel seeding
"interpolation": interpolation of data during tracking
"initial_dir": whether to seed tracts following the primary direction in a voxel, or a secondary one, or all of them. According to Frank, the tracking now always follows the primary direction
> MISC: Remove outdated dsi_studio tracking parameters

- qsiprep/cli/run.py
- qsiprep/workflows/base.py
- tests/smoke_tests.py
Closes none, but relates to the hackathon we're planning.
- Add `# fmt:skip` comments to the ends of `workflow.connect` calls, which will make any autoformatters and linters skip those calls. This will keep black (or whatever autoformatter we want) from messing up workflow connections, which are typically pretty ugly post-auto-formatting.
- Run black and isort on the file.
- Make minor changes to the docstrings.
- Remove an unused import.
- Remove unused parameters from `init_single_subject_wf`: skull_strip_template, skull_strip_fixed_seed, freesurfer, hires, prefer_dedicated_fmaps, and use_syn.
- I also removed the parameters from `init_qsiprep_wf` and added `(IGNORED)` to the descriptions of the related command line arguments.
> Apply stylistic changes to `workflows/base.py`

- pyproject.toml
Eventually we'll want to update the code to work with Nilearn 0.10.3, but in the meantime this will get QSIPrep working again.
- Pin Nilearn to 0.10.1.
> Pin Nilearn version

- .circleci/ScalarMapper.sh
- .circleci/config.yml
- pyproject.toml
- qsiprep/data/pipelines/bundle_scalar_map.json
- qsiprep/interfaces/interchange.py
- qsiprep/interfaces/recon_scalars.py
- qsiprep/interfaces/scalar_mapping.py
- qsiprep/workflows/recon/amico.py
- qsiprep/workflows/recon/build_workflow.py
- qsiprep/workflows/recon/converters.py
- qsiprep/workflows/recon/dipy.py
- qsiprep/workflows/recon/dsi_studio.py
- qsiprep/workflows/recon/mrtrix.py
- qsiprep/workflows/recon/pyafq.py
- qsiprep/workflows/recon/scalar_mapping.py
- qsiprep/workflows/recon/tortoise.py
These nodes will collect scalar images produced by the recon workflows and make them available to a "mapper" that can summarize them by atlases or bundles.
Interfaces to add:
> [ENH] Add ReconScalars node to recon workflows

- qsiprep/interfaces/dsi_studio.py
- qsiprep/interfaces/dwi_merge.py
- qsiprep/interfaces/eddy.py
- qsiprep/workflows/dwi/base.py
- qsiprep/workflows/dwi/fsl.py
- qsiprep/workflows/dwi/hmc_sdc.py
- qsiprep/workflows/dwi/merge.py
- qsiprep/workflows/dwi/pre_hmc.py
Eddy-CUDA has a slice-to-volume motion correction method. It is enabled by the `--mporder <int>` flag and requires that slice times and multiband acceleration factor are defined.
Currently users are accessing this feature by creating their own slice-timing file and mounting it into the container, along with specifying the other options in the eddy config json file (eg #184). This is a lot of extra work and not robust if there are different slice timings in different scans.
The trickiest part here is figuring out what the slice timings should be if there are multiple scans being concatenated before they're sent to Eddy. If the slice timings are too different, qsiprep should detect it early and exit. We discussed that a 10ms difference in a slice's timing across scans is acceptable. 
I …
> [ENH] Make Eddy's slice2vol much easier to use

- Dockerfile
well, the experiment of getting to the same ubuntu as nipreps failed. In practice the gpus on compute clusters are old and have old drivers. This PR reverts ubuntu to 18.04 so an older cuda can be used for drbuddi
> [FIX] Switch back to 18.04

- pyproject.toml
Pins a more current version of pyAFQ. 
Would this require testing beyond the CI on this PR?
> MAINT: Pin current version of pyAFQ (1.3.1)

- qsiprep/interfaces/anatomical.py
- qsiprep/workflows/recon/anatomical.py
Recon workflows were missing the processed anatomical data when `--anat-modality T2w` was used for preprocessing. This fixes that
> [FIX] recon workflows when --anat-modality T2w was used 

- qsiprep/workflows/recon/pyafq.py
Issue is described [here](https://neurostars.org/t/qsi-reconstruction-writes-to-work-dir-but-not-derivatives/29209/1).
The PyAFQ workflows needed a `"qsirecon_suffix"` in their datasink.
> [FIX] PyAFQ was not being written to derivatives

- qsiprep/interfaces/epi_fmap.py
The argsort function when used on the averaged cross correlations was producing unpredictable ranks.
This PR may help pick topup reference images more robustly
> [FIX] stop bizarre argsort behavior in best b=0

- .circleci/FreeSurferIngressTest.sh
- .circleci/get_data.sh
- .circleci/test_5tt_hsv.json
- qsiprep/config.py
- qsiprep/interfaces/bids.py
- qsiprep/interfaces/freesurfer.py
- qsiprep/interfaces/interchange.py
- qsiprep/workflows/recon/anatomical.py
- qsiprep/workflows/recon/base.py
Addresses #718 and numerous neurostars issues. This fixes the hsvs workflow (specifically the FreeSurfer ingression) which got very broken when we moved to the nipreps config model.
> [FIX] Make hsvs workflow work

- qsiprep/workflows/dwi/fsl.py
Eddy is currently getting threads from `omp_nthreads`. However, eddy_cuda only works if `--nthr=1`. This will set the threads for eddy depending on the `use_cuda` key in eddy_config. Fixes #747.
Tested locally and it works. Will not catch the cases where `use_cuda` is True but no GPU is passed to container and then reverts to `eddy_cpu`
> [FIX]: CUDA threads for Eddy

- qsiprep/workflows/dwi/merge.py
Closes #775. In #679, we added support for complex-valued denoising, but _only_ if `--denoise-after-combining` isn't used. This removes a connection from when I tried supporting complex-valued denoising when `--denoise-after-combining` is used.
It looks like this bug was found by running `--denoise-after-combining`. @mattcieslak any chance we could modify one of the tests to use `--denoise-after-combining`? Not sure if there are any test datasets with multiple runs.
- Remove expected `out_dwi_phase` output from `merge_dwis` node.
> Fix bad phase connection when using `--denoise-after-combining`

- docs/quickstart.rst
- qsiprep/interfaces/images.py
> [FIX] Change to Linear for upsampling

- qsiprep/interfaces/ants.py
- qsiprep/workflows/dwi/intramodal_template.py
Intramodal template was using too many threads and making HPCs unhappy.
> [FIX] Constrain threading for intramodal template

- qsiprep/interfaces/anatomical.py
- qsiprep/interfaces/reports.py
- qsiprep/workflows/anatomical/surface.py
Should help with #823.
- Add MNIInfant to allowed values for `SubjectSummary`'s `template` input.
- Remove some unused constants related to templates.
> Add MNIInfant to template enum

- qsiprep/cli/parser.py
This PR removes [pkgutil.find_loader()][] and replaces it with [importlib.util.find_spec()][]. `find_loader` was deprecated in Python 3.12 and will be removed in 3.14. `find_spec` has been present since Python 3.4.
Both functions return `None` if the module loader cannot be found. For its use in this project, this is sufficient and no translation of the return value is needed.
[pkgutil.find_loader()]: https://docs.python.org/3/library/pkgutil.html#pkgutil.get_loader
[importlib.util.find_spec()]: https://docs.python.org/3/library/importlib.html#importlib.util.find_spec
> rf(py314): Replace deprecated pkgutil.find_loader

- qsiprep/cli/parser.py
The ability to ignore phase data was added in #679, but it looks like it was accidentally removed in #745. This PR adds it back in.
- Add "phase" option to `--ignore` parameter.
> Add ability to ignore phase data

- qsiprep/workflows/base.py
- qsiprep/workflows/dwi/distortion_group_merge.py
Closes #838.
- Replace nonexistent config value with merged source filename in `init_distortion_group_merge_wf`.
> Use correct base name with `--distortion-group-merge average`

- .circleci/AllFieldmaps.sh
- .circleci/CUDATest.sh
- .circleci/DRBUDDI_eddy_rpe_series.sh
- .circleci/DSCSDSI.sh
- .circleci/DSDTI_TOPUP.sh
- .circleci/HBCD_preproc.sh
- .circleci/IntramodalTemplate.sh
- docs/preprocessing.rst
- qsiprep/cli/parser.py
- qsiprep/tests/test_cli.py
Closes none. This is a breaking change because parameter names have effectively been changed.
- Remove underscore versions of all parameters (e.g., `--anat_only` instead of `--anat-only`).
- Add dash versions where they were missing.
> Remove underscore versions of all parameters

- docs/preprocessing.rst
Closes none.
- Document the transforms written out by QSIPrep, including anat-to-ACPC and ACPC-to-template.
- Document the transforms not currently written out by QSIPrep, including the motion+eddy+SDC transform and the dwiref-to-ACPC transform.
> Document the transforms produced by QSIPrep

- qsiprep/utils/bids.py
Closes none.
- Compare metadata dictionaries across runs in a merge group and compile the metadata fields that are consistent across runs. This then goes in the merged JSON file. QSIRecon can reference the metadata fields at the top level of the JSON.
- In cases where the constituent runs don't have the same value for a given field, that field will be represented in the "SourceMetadata" field, but not in the top level of the JSON.
- Rename "scan_grouping" field to "ScanGrouping".  **THIS IS A BREAKING CHANGE**
- Rename "source_metadata" field to "SourceMetadata". **THIS IS A BREAKING CHANGE**
- Add "Sources" field to the JSON. I want to change all of the paths to BIDS-URIs in the future, but it's not a high priority item.
> Move common metadata to top of JSON

- qsiprep/data/reports-spec.yml
This is just until the next nireports release is made, since GIFs aren't supported yet and that's breaking the HTML report generation.
- Hardcode extensions for figures that are actually GIFs as PNGs so they get skipped until nireports can support GIFs.
> Hardcode extensions for GIF figures

- qsiprep/workflows/fieldmap/pepolar.py
I found this when testing the HBCD data locally. We don't have any T2w anat CI tests, so this flew under the radar
> [FIX] synthstrip extra arg

- pyproject.toml
- qsiprep/data/reports-spec.yml
Closes none. Overrides the changes in #880.
- Stop hardcoding extensions for GIF figures.
- Pin Nireports version to one that supports GIFs.
> Pin nireports version and allow GIFs

- qsiprep/interfaces/dsi_studio.py
Closes none, but addresses a bug identified by @tientong98. Instead of formatting a string for a logger message, we were passing in the initial string and a variable as separate arguments, which raises an error.
> Fix logger error

- qsiprep/cli/parser.py
- qsiprep/data/boilerplate.bib
- qsiprep/workflows/dwi/hmc.py
- qsiprep/workflows/dwi/merge.py
- qsiprep/workflows/fieldmap/syn.py
Closes #845.
- When using `--denoise-method dwidenoise` and `--dwi-denoise-window auto`, replace default value of 5 with what we _think_ dwidenoise's default value will be based on the number of volumes in the DWI run.
- Ignore `--dwi-denoise-window` when using `patch2self`.
- Raise an error at the parsing step if a user selects a non-default value for `--dwi-denoise-window` _and_ either `--denoise-method none` or `--denoise-method patch2self`.
- Check that `--dwi-denoise-window` is a positive, odd integer when it is supplied.
- Update the boilerplate to include the new dwi-denoise-window value.
> Calculate patch radius from number of volumes in DWI run

- qsiprep/cli/parser.py
- qsiprep/utils/bids.py
Closes none, but addresses two bugs identified by @araikes.
- Directly merge "session_id" (from the processing list) into the BIDS queries (which include the BIDS filters, which in turn may include "session") within `collect_data`.
- This should fix a bug that comes from using `--subject-anatomical-reference sessionwise` in combination with a `--bids-filter-file` that includes `session` fields.
- Limit session-wise processing to sessions with DWI data.
- This should fix a bug that comes from using `--subject-anatomical-reference sessionwise` on a dataset where some sessions have anatomical data without a corresponding DWI scan.
> Fix session processing for datasets with mixed modalities

- qsiprep/data/eddy_params.json
Change the default eddy flm from linear to quadratic. This matches the eddy default.
The slm remains linear, as recommended for lower-resolution data.
I don't think the defaults are mentioned in the docs.
> ENH: Update eddy_params.json

- docs/preprocessing.rst
- docs/quickstart.rst
- qsiprep/tests/test_utils_grouping.py
- qsiprep/utils/grouping.py
Closes #897 and reverts #862.
- Modify `get_entity_groups` to use the `MultipartID` metadata field when available.
- ~~If `MultipartID` is present for some files, but not others, then the function will treat all of the files without the field as belonging to the same group. Now that I think about it, we probably want them to be treated as belonging to separate groups, right? I can make that change depending on what @mattcieslak thinks.~~
- If `MultipartID` is present for some files, but not others, then the function will treat each file without the field as belonging to its own group.
- Stop grouping by acquisition entity by default. If users want to apply more sophisticated grouping logic, they can use `MultipartID`.
- Test `get_entity_groups`'s  behavior on simulated datasets with and …
> Group DWI scans by MultipartID when available

- docs/conf.py
- docs/preprocessing.rst
- qsiprep/cli/parser.py
- qsiprep/workflows/dwi/merge.py
Closes #932.
- Add notes on disabling B1 bias correction on prescan-normalized data to documentation.
> Add tips on B1 bias correction on normed data

- qsiprep/interfaces/gradients.py
- qsiprep/workflows/dwi/hmc.py
- qsiprep/workflows/dwi/hmc_sdc.py
Closes none, but is related to #301. In #301, the source_file parameter in CombineMotions became unused, so this PR just removes the parameter to make the code more readable.
- Remove source_file from CombineMotions and clean up related functions and workflows.
> Remove unused source_file parameter from CombineMotions

- qsiprep/tests/data/skeleton_complex_b0fields.yml
- qsiprep/tests/data/skeleton_complex_relpaths.yml
- qsiprep/tests/data/skeleton_fmap_b0fields.yml
- qsiprep/tests/test_utils_grouping.py
- qsiprep/utils/grouping.py
- qsiprep/workflows/base.py
Closes none.
- Write tests to cover field map collection and DWI scan grouping, using mocked up datasets.
- Modify the utility function `group_dwi_scans` to accept the BIDSLayout as a parameter instead of relying on the config object. This makes it easier to test. Also the nipreps folks only use the config in workflow functions. They tend to pass fields from it into interfaces and utility functions.
> Test dMRI and field map file grouping

- qsiprep/interfaces/dwi_merge.py
Closes #942.
- Modify `merge_dwis` so it works if `b0_mean` is NaN _or_ `correction` is.
> Work around NaNs in merge_dwis
